// Generated by CoffeeScript 1.4.0
(function() {
  var ctx;

  ctx = document.getElementById("game").getContext("2d");

  ctx.fillStyle = "#000";

  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);

}).call(this);
